#!/bin/bash

### BEGIN INIT INFO
# Provides:          gosecure
# Required-Start:    $all
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     2
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Go Secure: Simple SSL Tunnel
### END INIT INFO


do_start() {
	/opt/gosecure/gosecure.start
	sleep 1
}

do_stop() {

	/opt/gosecure/gosecure.stop
	sleep 1
}


case "$1" in 
	start)
		do_start
	;;
	stop)
		do_stop
	;;
	restart)
		do_stop
		do_start
	;;
	*)
		echo "usage: $0 [start|stop]"
		exit 1
	;;
esac


